settings = {
    "width": 10,
    "depth": 10,
    "height_multiplier": 1,
    "resolution": 48,
    "scale": 10,
    "max_angle": 90,
    "tree_density": 1,
    "rock_density": 1,
    "total_obstacles": 1,
    "mesh_rgba": [0, 128, 0, 1],  # the color the mesh will be
    "obstacle_items": [],
    "total_grass": 0,
    "grass_items": [],
    "noise_type": "Perlin",
    "noise_options": {
        "fractal_octaves": 2,
        "fractal_gain": 0.5,
        "fractal_lacunarity": 2,
        "frequency": 0.1,
        "fractal_type": "FBM",
        "perturb_type": "NoPerturb",
        "perturb_amp": 1,
        "perturb_frequency": 0.5,
        "perturb_gain": 0.5,
        "perturb_octaves": 3,
        "perturb_lacunarity": 2.0,
        "perturb_normalise_length": 1.0,
        "cellular_return_type": "Distance",
        "cellular_distance_function": "Euclidean",
        "cellular_jitter": 0.45,
        "cellular_lookup_frequency": 0.2,
    },
}
